-- ============================================================================
-- CREATE SUPER ADMIN USER - duncanmarshel@gmail.com
-- ============================================================================
-- This script creates a super admin user with full system access and control
-- Password: Marshel@1992
-- Email: duncanmarshel@gmail.com
-- 
-- IMPORTANT: 
-- 1. First create the user in Supabase Authentication (see instructions below)
-- 2. Then run this SQL script to set up the profile with super_admin role
-- 3. The user ID will be the UUID generated by Supabase auth
-- ============================================================================

-- STEP 1: Replace {USER_ID} with the actual UUID from Supabase auth
-- You'll get this UUID after creating the user in Supabase Authentication

-- Insert the super admin profile
INSERT INTO public.profiles (
  id,
  email,
  first_name,
  last_name,
  phone,
  role,
  status,
  is_active,
  email_confirmed,
  email_confirmed_at,
  created_at,
  updated_at
) VALUES (
  '0cef7b99-69ab-4a16-ba5b-b76fb0295e7e',  -- Replace with the actual UUID from Supabase auth
  'duncanmarshel@gmail.com',
  'Duncan',
  'Marshel',
  NULL,
  'super_admin',
  'active',
  true,
  true,
  NOW(),
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  role = 'super_admin',
  status = 'active',
  is_active = true,
  email_confirmed = true,
  updated_at = NOW();

-- Verify the profile was created
SELECT id, email, full_name, role, status, is_active FROM public.profiles 
WHERE email = 'duncanmarshel@gmail.com';

-- ============================================================================
-- Additional Permissions Setup (if using custom roles table)
-- ============================================================================

-- Ensure super_admin role exists in roles table
INSERT INTO public.roles (name, description, permissions, is_default)
VALUES (
  'super_admin',
  'Super Administrator with full system access',
  ARRAY[
    '*',
    'manage_all_properties',
    'manage_all_users',
    'manage_all_leases',
    'manage_all_payments',
    'manage_approvals',
    'manage_settings',
    'view_analytics',
    'manage_refunds',
    'manage_managers',
    'manage_maintenance',
    'view_audit_logs',
    'manage_system'
  ],
  false
)
ON CONFLICT (name) DO NOTHING;

-- Assign super_admin role to the user (if using user_roles table)
-- Uncomment if you have a user_roles junction table:
-- INSERT INTO public.user_roles (user_id, role_id, assigned_at)
-- SELECT 
--   '0cef7b99-69ab-4a16-ba5b-b76fb0295e7e',
--   (SELECT id FROM public.roles WHERE name = 'super_admin'),
--   NOW()
-- ON CONFLICT DO NOTHING;

-- ============================================================================
-- Verification Queries
-- ============================================================================

-- Verify super admin exists
SELECT 
  p.id,
  p.email,
  p.first_name,
  p.last_name,
  p.role,
  p.status,
  p.is_active,
  p.email_confirmed,
  p.created_at
FROM public.profiles p
WHERE p.email = 'duncanmarshel@gmail.com';

-- Count total profiles
SELECT COUNT(*) as total_profiles FROM public.profiles;

-- Show all super_admin users
SELECT id, email, role, status FROM public.profiles WHERE role = 'super_admin';
