#!/bin/bash
# FULLSTACK INTEGRATION DEPLOYMENT GUIDE
# Date: February 2, 2026
# This script helps deploy the fullstack integration fixes

set -e  # Exit on error

echo "=========================================="
echo "FULLSTACK INTEGRATION DEPLOYMENT GUIDE"
echo "=========================================="
echo ""
echo "This guide will help you deploy all fullstack integration fixes."
echo "Total time: ~5 minutes"
echo ""

# Step 1: Backup check
echo "STEP 1: Verification"
echo "  - Ensure you have Supabase project access"
echo "  - Ensure you have database admin permissions"
echo "  - Have a super_admin account ready"
echo ""
echo "Press ENTER when ready to continue..."
read

# Step 2: Display files to be applied
echo "STEP 2: Files to Apply (in order)"
echo "  1. 20260202_cleanup_and_reset_users.sql"
echo "     └─ Cleans up test users, preserves super_admin"
echo ""
echo "  2. 20260202_comprehensive_fullstack_alignment.sql"
echo "     └─ Unifies user model, adds RLS, creates views"
echo ""
echo "  3. 20260202_validation_tests.sql"
echo "     └─ Validates everything is working correctly"
echo ""
echo "These files are in: supabase/migrations/"
echo ""

# Step 3: Preparation
echo "STEP 3: Before Applying"
echo ""
echo "Choose your deployment path:"
echo ""
echo "A) FULL RESET (recommended for testing)"
echo "   - Cleans all users except super_admin"
echo "   - Best for: Testing, staging environments"
echo "   - Time: ~2 minutes"
echo ""
echo "B) ALIGNED ONLY (keep existing data)"
echo "   - Skips cleanup, just aligns schema"
echo "   - Best for: Production with existing data"
echo "   - Time: ~1 minute"
echo ""
echo "Enter A or B:"
read CHOICE

if [ "$CHOICE" = "A" ] || [ "$CHOICE" = "a" ]; then
    echo ""
    echo "PATH A SELECTED: Full Reset"
    echo "  You will need to:"
    echo "  1. Apply cleanup_and_reset_users.sql in Supabase SQL editor"
    echo "  2. Manually delete non-super_admin users from Auth > Users"
    echo "  3. Clear browser localStorage"
    echo ""
elif [ "$CHOICE" = "B" ] || [ "$CHOICE" = "b" ]; then
    echo ""
    echo "PATH B SELECTED: Schema Alignment Only"
    echo "  This will:"
    echo "  1. Skip the cleanup script"
    echo "  2. Apply alignment changes"
    echo "  3. Run validation"
    echo ""
else
    echo "Invalid choice. Exiting."
    exit 1
fi

echo "Press ENTER to see deployment instructions..."
read

echo ""
echo "=========================================="
echo "DEPLOYMENT INSTRUCTIONS"
echo "=========================================="
echo ""

if [ "$CHOICE" = "A" ] || [ "$CHOICE" = "a" ]; then
    echo "STEP 1: Run Cleanup Script"
    echo "  1. Go to: https://supabase.io"
    echo "  2. Select your project"
    echo "  3. Go to: SQL Editor > New Query"
    echo "  4. Copy contents of:"
    echo "     → supabase/migrations/20260202_cleanup_and_reset_users.sql"
    echo "  5. Run the query"
    echo "  6. Verify output shows users cleaned"
    echo ""
    echo "STEP 2: Manual Auth Cleanup"
    echo "  1. Go to: Authentication > Users"
    echo "  2. Delete ALL users EXCEPT the super_admin"
    echo "  3. Verify only super_admin remains"
    echo ""
fi

echo "STEP 3: Apply Alignment Migration"
echo "  1. Go to: SQL Editor > New Query"
echo "  2. Copy contents of:"
echo "     → supabase/migrations/20260202_comprehensive_fullstack_alignment.sql"
echo "  3. Run the query"
echo "  4. Wait for completion (~30 seconds)"
echo "  5. Verify output shows 'Fullstack alignment complete!'"
echo ""

echo "STEP 4: Run Validation Tests"
echo "  1. Go to: SQL Editor > New Query"
echo "  2. Copy contents of:"
echo "     → supabase/migrations/20260202_validation_tests.sql"
echo "  3. Run the query"
echo "  4. Verify all test results:"
echo "     - Profiles Table Structure: 15 columns"
echo "     - Valid Role Values: Shows roles used"
echo "     - Foreign Key Constraints: All relationships"
echo "     - Auth Trigger: Should show trigger exists"
echo "     - Orphaned Users: Should be 0"
echo ""

echo "STEP 5: Frontend Verification"
echo "  1. Frontend files already updated:"
echo "     ✓ src/services/userService.ts"
echo "     ✓ src/types/user.types.ts"
echo "     ✓ src/contexts/AuthContext.tsx"
echo ""
echo "  2. Build and run your app:"
echo "     npm run dev"
echo ""
echo "  3. Test registration:"
echo "     - Sign up with new account"
echo "     - Verify profile created in database"
echo "     - Check role assignment works"
echo ""

echo "STEP 6: Testing Checklist"
echo "  [ ] Registration flow works"
echo "  [ ] User profile loads correctly"
echo "  [ ] Role-based access works"
echo "  [ ] Property manager can see properties"
echo "  [ ] Tenant can see assigned unit"
echo "  [ ] Super admin sees all data"
echo ""

echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "If registration fails:"
echo "  1. Check auth.users table"
echo "  2. Run: SELECT * FROM public.profiles WHERE email = '<user-email>'"
echo "  3. Verify row exists"
echo "  4. Check error logs in browser console"
echo ""

echo "If RLS causes 'no rows' errors:"
echo "  1. Verify user's role in profiles table"
echo "  2. Check RLS policy logic"
echo "  3. Ensure auth.uid() returns correct value"
echo "  4. Test with super_admin first"
echo ""

echo "If views don't exist:"
echo "  1. Run validation tests again"
echo "  2. Check for SQL errors"
echo "  3. Manually create: CREATE VIEW tenant_profile_view ..."
echo ""

echo "=========================================="
echo "SUPPORT"
echo "=========================================="
echo ""
echo "For detailed info, see:"
echo "  → FULLSTACK_INTEGRATION_COMPLETE.md"
echo ""
echo "For migration details:"
echo "  → supabase/migrations/20260202_*.sql"
echo ""
echo "=========================================="
echo ""
echo "Setup complete! Your fullstack app is now integrated. 🎉"
echo ""
